### ISSUE TITLE
Dependency on crypto lib version < 1 prevents installation

### ISSUE THREAD

**Issue by ahenket** [eXistSolutions/exist-jwt#9]
JWT 1.1.1 has a dependency on crypto lib < 1 instead of >= 1

```xml
<dependency package="http://expath.org/ns/crypto" semver-max="1"/>
```

I believe that should have been 

```xml
<dependency package="http://expath.org/ns/crypto" semver-min="1"/>
```

**Comment by line-o** [comment]
That dependency is declared on purpose because the next version of the crypto lib (v5.3.0) was broken.

**Comment by line-o** [comment]
related #8
